# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'salik_tollgate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets

g = "none"

#create database
conn = sqlite3.connect('project.db')
c = conn.cursor()
c.execute("""CREATE TABLE if not exists tollgate(
    vehicle_name text,
    reg_num VARCHAR(100),
    date TIMESTAMP,
    vehicle_type text,
    toll_charges INTEGER 
)"""
)

conn.commit()

conn.close()


class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 789)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 80, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 339, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 310, 122, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 310, 183, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 339, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(140, 414, 129, 19))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 390, 129, 19))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(430, 430, 174, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.toggled.connect(self.minicarselected)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(430, 460, 174, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.toggled.connect(self.sedancarselected)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(430, 490, 174, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_3.toggled.connect(self.suvselected)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(430, 520, 174, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_4.toggled.connect(self.truckselected)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 390, 174, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 600, 151, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(430, 550, 251, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_5.toggled.connect(self.emergencyselected)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(140, 570, 201, 54))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_7 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(690, 190, 650, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 140, 100, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(800, 140, 100, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(910, 140, 100, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1020, 140, 100, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1130, 140, 100, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1240, 140, 100, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(690, 650, 183, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
       
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.radioButton_5, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.dateTimeEdit)
        MainWindow.setTabOrder(self.dateTimeEdit, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_4)

        



        self.pushButton.clicked.connect(self.save_it)
        self.pushButton_2.clicked.connect(self.all_vehicle)
        self.pushButton_3.clicked.connect(self.mini_car)
        self.pushButton_4.clicked.connect(self.sedan)
        self.pushButton_5.clicked.connect(self.suv)
        self.pushButton_6.clicked.connect(self.truck)
        self.pushButton_7.clicked.connect(self.emergency)
        

    
    def minicarselected(self, selected):
        if selected:
            self.lineEdit_4.setText("2")
            g = "Mini Car"
            print(g)
    def sedancarselected(self, selected):
        if selected:
            self.lineEdit_4.setText("3")
            g = "Sedan"
            print(g)
    def suvselected(self, selected):
        if selected:
            self.lineEdit_4.setText("4")
            g = "SUV"
            print(g)
    def truckselected(self, selected):
        if selected:
            self.lineEdit_4.setText("8")
            g = "Truck/Bus/Coach"
            print(g)
    def emergencyselected(self, selected):
        if selected:
            self.lineEdit_4.setText("0")
            g = "Emergency Vehicle"
            print(g)
    
    def save_it(self):
        print(self.lineEdit.text())
        print(self.lineEdit_2.text())
        print(self.lineEdit_4.text())
        print(self.dateTimeEdit.text())
        if self.radioButton.isChecked():
            g = "Mini Car"
            
        elif self.radioButton_2.isChecked():
            g = "Sedan"
            
        elif self.radioButton_3.isChecked():
            g = "SUV"
            
        elif self.radioButton_4.isChecked():
            g = "Truck/Bus/Coach"
            
        elif self.radioButton_5.isChecked():
            g = "Emergency Vehicle"
            
        print(g)

        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        c.execute("INSERT INTO tollgate values(?,?,?,?,?)",(self.lineEdit.text(), self.lineEdit_2.text(), self.dateTimeEdit.text(), g, self.lineEdit_4.text()))

        conn.commit()

        conn.close()
        self.lineEdit.clear()
        self.lineEdit_2.clear()

        
    

    def all_vehicle(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()


    def mini_car(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate where toll_charges = 2 ")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate where toll_charges = 2")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()


    def sedan(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate where toll_charges = 3 ")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate where toll_charges = 3")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()


    def suv(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate where toll_charges = 4 ")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate where toll_charges = 4")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()


    def truck(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate where toll_charges = 8 ")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate where toll_charges = 8")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()

    def emergency(self):
        conn = sqlite3.connect('project.db')

        c = conn.cursor()

        result = c.execute("SELECT * FROM tollgate where toll_charges = 0 ")

        
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))
        
        # records = c.fetchall()

        # for record in records:
        #     self.columnView.addItem(str(record))
        sum = c.execute("SELECT SUM(toll_charges) from tollgate where toll_charges = 0")
        sum = sum.fetchone()
        self.label_8.setText("Total Toll: "+str(sum[0]) + " AED")
        


        conn.commit()

        conn.close()

    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Salik Tollgate"))
        self.label_2.setText(_translate("MainWindow", "Enter Vehicle Details"))
        self.label_3.setText(_translate("MainWindow", "Vehicle Name"))
        self.label_4.setText(_translate("MainWindow", "Registration Number"))
        self.label_5.setText(_translate("MainWindow", "Date "))
        self.radioButton.setText(_translate("MainWindow", "Mini Car"))
        self.radioButton_2.setText(_translate("MainWindow", "Sedan"))
        self.radioButton_3.setText(_translate("MainWindow", "SUV"))
        self.radioButton_4.setText(_translate("MainWindow", "Truck/Bus/Coach"))
        self.label_6.setText(_translate("MainWindow", "Vehicle Type"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.radioButton_5.setText(_translate("MainWindow", "Emergency Vehicle"))
        self.label_7.setText(_translate("MainWindow", "Toll Charges"))
        
        
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "All Vehicle"))
        self.pushButton_3.setText(_translate("MainWindow", "Mini Car"))
        self.pushButton_4.setText(_translate("MainWindow", "Sedan"))
        self.pushButton_5.setText(_translate("MainWindow", "SUV"))
        self.pushButton_6.setText(_translate("MainWindow", "Truck/Bus/Coach"))
        self.pushButton_7.setText(_translate("MainWindow", "Emergency Vehicle"))
        self.label_8.setText(_translate("MainWindow", "Total Toll "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vehicle Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Registration Num."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vehicle Type"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Toll Charges"))

    

        
        


        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
